require '../sort_ld_frameworks.rb'

use_frameworks!

platform :ios, '13.0'

target 'Vision_Example' do
  pod 'Vision', :path => '../'

  target 'Vision_Tests' do
    inherit! :search_paths

    
  end
end
